### ISSUE TITLE
Crash when attempting to open "Characters" tab of new Warhammer 40k: 10th Edition data

### ISSUE THREAD

**Issue by Zakading** [BlueWinds/bluescribe#22]
I was atempting to build a Space Marine/Black Templar roster using the newly added 10th edition data, however as soon as I attempt to open the "Characters" tab in the unit selection, the site immediately puts me to this error page:
![chrome_2023-07-24_15-16-28](https://github.com/BlueWinds/bluescribe/assets/23154483/77222583-915e-4775-b72b-dd11d46bb72e)
Afterwards, I need to entirely clear the data and reload it to even start creating a new roster again.

**Comment by BlueWinds** [comment]
Thanks for the report, should be fixed now!

There's an error in the 10e data around the Chaplain, which BlueScribe wasn't catching properly; I've fixed it so that things will work. Gracefully handling issues with the input data isn't BlueScribes' strongest trait at the moment, it assumes that the game data is consistent and reliable (bad assumption).
